### ISSUE TITLE
Windows setup gems Error

### ISSUE THREAD

**Issue by Jirapong** [shoes/shoes-deprecated#179]
On the statement 

```
Shoes.setup do 
    gem 'activesupport = 3.0.0'
end
```

the gem download and install successfully but then error occur in Console 

```
No such file or directory - C
C:/Shoes/0.r15414/lib/shoes.rb:439:in 'read'
C:/Shoes/0.r15414/lib/shoes.rb:439:in 'read_file'
C:/Shoes/0.r15414/lib/shoes.rb:427:in 'visit'
C:/Shoes/0.r15414/lib/shoes/setup.rb:75:in 'block (2 levels)'
```

but after close the console, and re-load the app. It work fine.

**Comment by jrgifford** [comment]
So what you're saying here is the first time you run your application, it crashes, and then after you quit and start it again, it works fine?

**Comment by Jirapong** [comment]
Yes, That's correct. my investigation is to shoes.rb#visit method has a bug. 

   def self.visit(path)
    uri = Shoes.uri(path)

```
case uri 
when URI::HTTP
  str = uri.read
  if str !~ /Shoes\.app/
    Shoes.app do
      eval(uri.read)
    end 
  else
    eval(uri.read)
  end 
else
  path = File.expand_path(path.gsub(/\\/, "/"))
  debug("Path: #{path}")
  if path =~ /\.shy$/
    @shy = true
    require 'shoes/shy'
    base = File.basename(path, ".shy")
    tmpdir = "%s/shoes-%s.%d" % [Dir.tmpdir, base, $$] 
    shy = Shy.x(path, tmpdir)
    Dir.chdir(tmpdir)
    Shoes.debug "Loaded SHY: #{shy.name} #{shy.version} by #{shy.creator}"
    path = shy.launch
  else
    @shy = false
    dir = File.dirname(path)
    Dir.chdir(dir)
    path = File.basename(path)
  end 

  $0.replace path
  if (path == 'C') << My workaround at this point
     path = 'myapp.rb'
  end 

  code = read_file(path)
  eval(code, TOPLEVEL_BINDING, path)
end 
 rescue SettingUp
rescue Object => e
  error(e)
  showlog() << This is where the Dialog show up after first time run my app.
end 
```

is return something C:\Program Files\Common Files\Shoes..\C  instead of to return the startup ruby file. see my workaround  above.
