### ISSUE TITLE
Build for Windows XP +

### ISSUE THREAD

**Issue by pjfitzgibbons** [shoes/shoes-deprecated#190]
3.2 Walkabout.
Build for Windows XP +, 32bit
Make sure version and build name looks like this :
shoes-3.2.r####-walkabout-[platform].[suffix]

r#### is the build revision number.
[platform] and [suffix] are platform specific.

This should match the output of ./shoes -v, minus the suffix.

Upload to: 
https://github.com/shoes/shoes/downloads

**Comment by DouglasAllen** [comment]
Help please!
Topic is right but I don't understand what this particapant is saying.
My issue is building shoes on windows.
My output from rake command =
C:\shoes_dev>rake
"downloading http://easynews.dl.sourceforge.net/mingw/mingwrt-3.15.2-mingw32-dll.tar.gz to C:/sh
oes_dev/downloads/mingwrt-3.15.2-mingw32-dll.tar.gz"
WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method URI::HTTP#verbose called at C:/shoes_dev/rake/contrib/uri_ext.rb:234:in `blo
ck in read'
Requesting http://easynews.dl.sourceforge.net/mingw/mingwrt-3.15.2-mingw32-dll.tar.gz
rake aborted!
getaddrinfo: No such host is known.

Tasks: TOP => default => download => compiler:mingw:download => C:/shoes_dev/downloads/mingwrt-3
.15.2-mingw32-dll.tar.gz
(See full trace by running task with --trace)

Could we get this installer updated please?
I downloaded everything from the site wget was trying to use on the wiki.
I don't know what you expected windows to do with that?
I have msysGit installed from the net installer but  there must be environment vars to be set I guess.(more docs on that needed)
No wget working here.
I have devkit but that is not used in the wiki.
I have Ruby-1.9.3-p194 but the wiki wants 1.9.2
What else can I complain about?
Just ask me.
I barley know how to use git.
Sorry!

**Comment by DouglasAllen** [comment]
No easynews on sourceforge according to my browser.

**Comment by DouglasAllen** [comment]
Could we please let ashbb know that this is not working for the rubyinstaller?
I tried changing the :url in the config/ruby_installer.rb to
http://www.rin-shun.com/shoes/MinGW/downloads
Then rake again =
C:\shoes_dev>rake
"downloading http://www.rin-shun.com/shoes/MinGW/downloads/mingwrt-3.15.2-mingw32-dll.tar.gz to
C:/shoes_dev/downloads/mingwrt-3.15.2-mingw32-dll.tar.gz"
WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method URI::HTTP#verbose called at C:/shoes_dev/rake/contrib/uri_ext.rb:234:in `blo
ck in read'
Requesting http://www.rin-shun.com/shoes/MinGW/downloads/mingwrt-3.15.2-mingw32-dll.tar.gz
WARNING: DSL method URI::HTTP#verbose called at C:/shoes_dev/rake/contrib/uri_ext.rb:249:in`blo
ck (2 levels) in read'
Downloading http://www.rin-shun.com/shoes/MinGW/downloads/mingwrt-3.15.2-mingw32-dll.tar.gz
rake aborted!
undefined method `path' for nil:NilClass

Tasks: TOP => default => download => compiler:mingw:download => C:/shoes_dev/downloads/mingwrt-3
.15.2-mingw32-dll.tar.gz
(See full trace by running task with --trace)

**Comment by DouglasAllen** [comment]
Like I stated previously, I have already downloaded everything from this directory =
http://www.rin-shun.com/shoes/MinGW/downloads/
Why should it be doing this again?

**Comment by jrgifford** [comment]
@DouglasAllen: Thank you for taking the time to report this.

@ashbb  - i'm sure you've seen this, but please see the thread above when you get the chance, I know you've got a busy schedule. :)

**Comment by DouglasAllen** [comment]
I have shoes working but just thought I might try to build it. Thanks @jrgifford

**Comment by ashbb** [comment]
@DouglasAllen 

> I have Ruby-1.9.3-p194 but the wiki wants 1.9.2

Are you using Ruby 1.9.3? If so, refer to [Red Shoes for Windows with Ruby 1.9.3p125](http://librelist.com/browser//shoes/2012/2/26/red-shoes-for-windows-with-ruby-1-9-3p125/).

But honestly I didn't build Red Shoes for Windows for over half a year. So, I'm not sure the article is still useful...

**Comment by DouglasAllen** [comment]
K! Thanks @ashbb 
I got some of the way into this by getting ride of all the download tasks that I did find in all the rake files. It went into extracting mode but when it got to this
rake aborted!
Command failed with status (2): ["C:/shoes_dev/sandbox/extract_utils/7z.exe...]

Tasks: TOP => default => extract => interpreter:ruby19:extract
(See full trace by running task with --trace)

Looking in the rake file C:\shoes_dev\recipes\interpreter\ruby19.rake there isn't an extract task defined.
I do have it from  http://www.rin-shun.com/shoes/MinGW/downloads/
which is 1.9.2 there.
Got access to that @ashbb ?
Maybe you could just drop in 1.9.3

**Comment by DouglasAllen** [comment]
ruby-1.9.3-p286.tar.gz is out now
and another shoes page is here
http://www.rin-shun.com/shoes/

**Comment by DouglasAllen** [comment]
@ashbb perhaps you could tell us what the rake files use for a downloader. I was not able to get any of that to work in spite of changing all the uri: to a known good.
It gave a status as it seemed to be downloading but aborted on the first one. That's when I decided to comment out all the :download tasks as I did so already from the given url.
I noticed that "C:/shoes_dev/downloads/ruby-1.9.3-p125.tar.bz2" > NUL
was just before the abort report that I posted here. So I'm getting it and will try again.
The url is http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p125.tar.gz

**Comment by ashbb** [comment]
@DouglasAllen Is your problem downloading dependency files?
If so, I'm so sorry to say nothing about that...
The rake-download-task doesn't work well. You have to download all files by hand.
After downloading all files by hand, you can do `rake`.
Then the rake skips downloading task and use files you already downloaded by hand.

**Comment by DouglasAllen** [comment]
@ashbb It didn't do that. I did what I stated before above. I got the newer ruby-1.9.3-p125.tar.gz and put it into the downloads dir. I had to change the config/ruby_installer.rb line 96 from 'ruby-1.9.3-p125.tar.bz2' to 'ruby-1.9.3-p125.tar.gz'
Then rake ran all the way to compiling until here
configuring etc
make: **\* [exts.mk] Error 1
rake aborted!
Command failed with status (2): ["C:/shoes_dev/sandbox/msys/bin/bash.exe" -...]

Tasks: TOP => default => source_dependency_compile => interpreter:ruby19:compile
(See full trace by running task with --trace)

Are there more dependencies than just the ones in the downloads folder?
I almost thought we had it. You guys amaze me what you do all this stuff like minGW and rake.
I wouldn't know where to begin. As it is I've got about three different installs of minGW and msys. One from the devkit, one from the msysGit, and this one. When will it ever end?
I had it all working a long time ago before I even heard of shoes. Now I hope it's getting easier to install.
So what does Ruby need to build? It seems to have failed.
Thanks again @ashbb 
If there is a build log somewhere would you want it?

**Comment by DouglasAllen** [comment]
I ran rake again from the C:\shoes_dev and this time there were no errors. But I still don't have a shoes folder in the sandbox.

**Comment by DouglasAllen** [comment]
I git clone https://github.com/ashbb/shoes.git in the sandbox. I went back to root C:\shoes_dev
I ran > rake interpreter:shoes:compile
Shoes seems to have built.

> C:\shoes_dev>rake installer
> rake aborted!
> Don't know how to build task 'installer'

(See full trace by running task with --trace)

Any notes on that? What directory should I be in?

**Comment by DouglasAllen** [comment]
shoes policeman (0.r1554) [i386-mingw32 Ruby1.9.3] which I have installed from shoes site but not sure which version of Ruby it uses. Let me check. No it is shoes policeman (0.r1514) [i386-mingw32 Ruby1.9.1] +video

I went and got http://vgoff.posterous.com/a-trial-of-building-red-shoes-for-windows-wit
http://www.rin-shun.com/shoes/shoes-0.r1777.exe
shoes policeman (0.r1777) [i386-mingw32 Ruby1.9.3]

Why isn't that listed on http://www.rin-shun.com/shoes/?
I'm going to drop ruby-1.9.3-p286.tar.gz into downloads and see if we can build it.

**Comment by DouglasAllen** [comment]
Yay! I built shoes with the newest Ruby. The shoes version is still shoes policeman (0.r1554) [i386-mingw32 Ruby1.9.3]
but that's shoes. I just dropped this distro into 0.r1554 of shoes where my other shoes live. Is there a shoes app command that will tell you the version of Ruby? I can see msvcrt-ruby191.dll with further info below saying 1.9.3.286 
Ruby interpreter (DLL) 1.9.3p286 [i386-mingw32] so I guess that's right.

**Comment by ashbb** [comment]
@DouglasAllen Wow, fantastic!

> Is there a shoes app command that will tell you the version of Ruby?

``` ruby
Shoes.app do
  para RUBY_VERSION, ' ', RUBY_PATCHLEVEL
end
```

> The shoes version is still shoes policeman (0.r1554)

Because you are using `ashbb/shoes/tree/master` branch.
Red Shoes version is the number of commit lists: `git rev-list HEAD`.split.length + 1

The `ashbb/shoes/tree/develop` is 0.r1805 now. The `shoes/shoes/tree/develop` is 0.r1823.
After 0.r1783, I've not tried to build Red Shoes. So, I'm not sure you can use the latest code for Windows, though... :-P

**Comment by DouglasAllen** [comment]
K! We are just discussing this @ http://vgoff.posterous.com/a-trial-of-building-red-shoes-for-windows-wit because I know he is very interested in shoes and by the way, did everyone get to see the video presentation he did as an interview with Steve http://www.youtube.com/watch?v=9UQI1iCqAx4

**Comment by PragTob** [comment]
That video is really nice to watch, watched it back then and it was awesome :-)
