### ISSUE TITLE
Packaging to exe - fails when running

### ISSUE THREAD

**Issue by aarmora** [shoes/shoes-deprecated#275]
Not sure what the issue is here.  I'm thinking maybe permissions?  But I'm not sure what process needs permission.

```
Error in <unknown> line 0 | 2015-07-01 23:26:34 +0000
No such file or directory @ rb_sysopen - scraper.rb
C:/Program Files (x86)/Shoes/lib/shoes.rb:517:in `read'
C:/Program Files (x86)/Shoes/lib/shoes.rb:517:in `read_file'
C:/Program Files (x86)/Shoes/lib/shoes.rb:496:in `visit'
eval:1:in `<main>'
```

This is the stack trace.  Any ideas?

**Comment by ccoupe** [comment]
@aarmora, you didn't mention which version of Shoes you are using the old 3.1 or the newer 3.2  that has it's own issue page at https://github.com/Shoes3/shoes3. If it's 3.2, that stack trace suggests you are attempting to run scraper.rb and it's not where it's supposed to be (I assume your testing the packaged exe and it's only one file (not a shy?).

**Comment by aarmora** [comment]
Cecil,

Yes, I am running 3.2, sorry about not mentioning that.

Scraper.rb is what I packaged.  I currently have them in the same
directory.  But shouldn't the executable be standalone or does it need the
file it was packaged from to also be present?

Thanks,

Jordan

**Comment by ccoupe** [comment]
Jordan, on Windows the script (or shy) inside the packaged.exe is expanded into %HOME%\AppData\Local\Shoes when run on the users machine (and deleted when Shoes is closed).  With the console error screen up, Shoes isn't closed so you should be able to look in there to make sure it is there and named correctly.  Please open a new issue at https://github.com/Shoes3/shoes3/issues so it can be tagged and followed.  Please mention which Windows version you are using and the Shoes 3.2.xx (or r(nnnn) number so I know how old it is.  Also, how you packaged it - 'download if needed' or 'include shoes' and whether you packaged from the command line or from the Shoes GUI.
